In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
Aadhaar_df=pd.read_csv(r"C:\Users\Lenovo\Desktop\UIDAI_Data_Hackathon_2026\data\combined\final_aadhar_data.csv")

In [3]:
Aadhaar_df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity
0,2025-03-01,Andaman & Nicobar Islands,Andamans,744101,0,0,0,0,0,16,193,209
1,2025-03-01,Andaman And Nicobar Islands,Nicobar,744301,0,0,0,32,360,101,48,541
2,2025-03-01,Andaman And Nicobar Islands,Nicobar,744302,0,0,0,0,0,15,12,27
3,2025-03-01,Andaman And Nicobar Islands,Nicobar,744303,0,0,0,0,0,46,27,73
4,2025-03-01,Andaman And Nicobar Islands,Nicobar,744304,0,0,0,0,0,16,14,30
...,...,...,...,...,...,...,...,...,...,...,...,...
2327255,2025-12-31,West Bengal,West Midnapore,721426,0,1,0,0,0,0,0,1
2327256,2025-12-31,West Bengal,West Midnapore,721504,1,0,0,0,0,0,0,1
2327257,2025-12-31,West Bengal,West Midnapore,721506,1,1,0,0,0,0,0,2
2327258,2025-12-31,West Bengal,West Midnapore,721507,1,0,0,0,0,0,0,1
2327259,2025-12-31,West Bengal,West Midnapore,721517,2,1,0,0,0,0,0,3

In [4]:
Aadhaar_df.shape

(2327260, 12)

In [5]:
Aadhaar_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2327260 entries, 0 to 2327259
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   date            object
 1   state           object
 2   district        object
 3   pincode         int64
 4   age_0_5         int64
 5   age_5_17        int64
 6   age_18_greater  int64
 7   demo_age_5_17   int64
 8   demo_age_17_    int64
 9   bio_age_5_17    int64
 10  bio_age_17_     int64
 11  total_activity  int64
dtypes: int64(9), object(3)
memory usage: 213.1+ MB

we observed date again become object we need to change it

In [6]:
Aadhaar_df.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity
0,2025-03-01,Andaman & Nicobar Islands,Andamans,744101,0,0,0,0,0,16,193,209
1,2025-03-01,Andaman And Nicobar Islands,Nicobar,744301,0,0,0,32,360,101,48,541
2,2025-03-01,Andaman And Nicobar Islands,Nicobar,744302,0,0,0,0,0,15,12,27
3,2025-03-01,Andaman And Nicobar Islands,Nicobar,744303,0,0,0,0,0,46,27,73
4,2025-03-01,Andaman And Nicobar Islands,Nicobar,744304,0,0,0,0,0,16,14,30

In [7]:
Aadhaar_df['date'] = pd.to_datetime(Aadhaar_df['date'], errors='coerce')

Aadhaar_df['date'].min(), Aadhaar_df['date'].max()

(Timestamp('2025-03-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

we changed date datatype into datetime64

In [8]:
Aadhaar_df.describe()

,date,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity
count,2327260,2.327260e+06,2.327260e+06,2.327260e+06,2.327260e+06,2.327260e+06,2.327260e+06,2.327260e+06,2.327260e+06,2.327260e+06
mean,2025-10-25 21:04:56.389058816,5.251727e+05,1.524095e+00,7.392315e-01,7.233958e-02,2.089764e+00,1.909188e+01,1.470693e+01,1.526956e+01,5.349380e+01
min,2025-03-01 00:00:00,1.000000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2025-09-20 00:00:00,3.943250e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
50%,2025-11-04 00:00:00,5.241290e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,2.000000e+00,2.000000e+00,1.200000e+01
75%,2025-12-05 00:00:00,6.905420e+05,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.200000e+01,8.000000e+00,8.000000e+00,3.600000e+01
max,2025-12-31 00:00:00,8.554560e+05,2.688000e+03,1.812000e+03,8.550000e+02,5.380000e+03,3.233200e+04,8.002000e+03,7.625000e+03,4.586100e+04
std,NaN,1.976129e+05,1.169165e+01,9.495850e+00,2.121569e+00,1.817912e+01,1.521344e+02,7.537931e+01,7.926850e+01,2.795450e+02

this are the numerical columns present in this data and the max and min values

In [15]:
Aadhaar_df['date'].min(), Aadhaar_df['date'].max()

(Timestamp('2025-03-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

In [16]:
Aadhaar_df['date'].dt.year.value_counts().sort_index()

date
2025    2327260
Name: count, dtype: int64

this is 2025 year count

In [17]:
Aadhaar_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2327260 entries, 0 to 2327259
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   date            datetime64[ns]
 1   state           object
 2   district        object
 3   pincode         int64
 4   age_0_5         int64
 5   age_5_17        int64
 6   age_18_greater  int64
 7   demo_age_5_17   int64
 8   demo_age_17_    int64
 9   bio_age_5_17    int64
 10  bio_age_17_     int64
 11  total_activity  int64
dtypes: datetime64[ns](1), int64(9), object(2)
memory usage: 213.1+ MB

In [18]:
activity_cols = [
    'age_0_5','age_5_17','age_18_greater',
    'demo_age_5_17','demo_age_17_',
    'bio_age_5_17','bio_age_17_'
]

Aadhaar_df['recalc_total'] = Aadhaar_df[activity_cols].sum(axis=1)

In [19]:
(Aadhaar_df['total_activity'] != Aadhaar_df['recalc_total']).value_counts()

False    2327260
Name: count, dtype: int64

In [20]:
Aadhaar_df['total_activity'] = Aadhaar_df['recalc_total']
Aadhaar_df.drop(columns='recalc_total', inplace=True)

In [21]:
Aadhaar_df.isna().sum()

date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
demo_age_5_17     0
demo_age_17_      0
bio_age_5_17      0
bio_age_17_       0
total_activity    0
dtype: int64

In [22]:
Aadhaar_df[activity_cols] = Aadhaar_df[activity_cols].fillna(0)

if incase there any empty columns in activity cols fill with 0

In [23]:
(Aadhaar_df[activity_cols] < 0).sum()

age_0_5           0
age_5_17          0
age_18_greater    0
demo_age_5_17     0
demo_age_17_      0
bio_age_5_17      0
bio_age_17_       0
dtype: int64

In [24]:
Aadhaar_df = Aadhaar_df[Aadhaar_df['total_activity'] > 0]

In [26]:
Aadhaar_df.shape

(2326550, 12)

state column cleaning

In [27]:
Aadhaar_df['state'].nunique(), Aadhaar_df['district'].nunique()

(60, 1002)

we observed that they are 60 state . i think there might be spelling mistakes

In [29]:
Aadhaar_df["state"].unique()

array(['Andaman & Nicobar Islands', 'Andaman And Nicobar Islands',
       'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli',
       'Dadra And Nagar Haveli',
       'Dadra And Nagar Haveli And Daman And Diu', 'Daman & Diu',
       'Daman And Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana',
       'Himachal Pradesh', 'Jammu And Kashmir', 'Jharkhand', 'Karnataka',
       'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Orissa',
       'Pondicherry', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim',
       'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal',
       'The Dadra And Nagar Haveli And Daman And Diu', 'Jammu & Kashmir',
       'West  Bengal', 'Westbengal', '100000', 'West Bangal',
       'Uttaranchal', 'Chhatisgarh', 'West Bengli', 'Balanagar',
       'Darbhanga', 'Puttenahalli', 'Nagpur', 'Jaipur',
       'Raja Annamalai Puram', 'Madanapalle', 'Tamilnadu'], dtype=object)

there are same name but different spillings of name

In [30]:
STATE_CORRECTIONS = {
    'orissa': 'odisha',
    'uttaranchal': 'uttarakhand',
    'pondicherry': 'puducherry',

    'jammu & kashmir': 'jammu and kashmir',
    'andaman & nicobar islands': 'andaman and nicobar islands',

    'dadra and nagar haveli': 'dadra and nagar haveli and daman and diu',
    'daman and diu': 'dadra and nagar haveli and daman and diu',
    'dadra & nagar haveli': 'dadra and nagar haveli and daman and diu',
    'daman & diu': 'dadra and nagar haveli and daman and diu',

    'westbengal': 'west bengal',
    'west bangal': 'west bengal',
    'west bengli': 'west bengal',

    'chhatisgarh': 'chhattisgarh'
}

we corrected the wrong name / old name into perfect names

In [31]:
OFFICIAL_STATES = {
    'andhra pradesh', 'arunachal pradesh', 'assam', 'bihar', 'chhattisgarh',
    'goa', 'gujarat', 'haryana', 'himachal pradesh', 'jharkhand',
    'karnataka', 'kerala', 'madhya pradesh', 'maharashtra',
    'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha',
    'punjab', 'rajasthan', 'sikkim', 'tamil nadu', 'telangana',
    'tripura', 'uttar pradesh', 'uttarakhand', 'west bengal',

    # Union Territories
    'andaman and nicobar islands', 'chandigarh', 'dadra and nagar haveli and daman and diu',
    'delhi', 'jammu and kashmir', 'ladakh', 'lakshadweep', 'puducherry'
}

we stating that orginal name of state and districts

In [32]:
Aadhaar_df['state_clean'] = (
    Aadhaar_df['state']
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace('&', 'and')
    .str.replace(r'\s+', ' ', regex=True)
)

is there any next line , and into & , " " and no space , lowervalue of state this formate for state

In [33]:
Aadhaar_df['is_numeric_state'] = Aadhaar_df['state_clean'].str.fullmatch(r'\d+')
Aadhaar_df['is_valid_state'] = Aadhaar_df['state_clean'].isin(OFFICIAL_STATES)

It creates validation flags to detect numeric and invalid state values for data cleaning.

In [34]:
Aadhaar_df['state_clean'] = Aadhaar_df['state_clean'].replace(STATE_CORRECTIONS)

it replace with valid state names

In [35]:
Aadhaar_df['state_final'] = np.where(
    Aadhaar_df['is_valid_state'] & ~Aadhaar_df['is_numeric_state'],
    Aadhaar_df['state_clean'],
    np.nan
)

the final state column is ready now

In [36]:
Aadhaar_df.state.nunique()

60

In [37]:
Aadhaar_df = Aadhaar_df.dropna(subset=['state_final'])

In [38]:
Aadhaar_df['state'] = Aadhaar_df['state_final']
Aadhaar_df = Aadhaar_df.drop(columns=['state_clean', 'state_final', 'is_numeric_state', 'is_valid_state'])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18900\2706748857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Aadhaar_df['state'] = Aadhaar_df['state_final']

now renameing state_final into state

In [39]:
Aadhaar_df['state'].nunique()

36

we go the 36 perfect state count of india

In [41]:
Aadhaar_df.shape

(2303050, 12)

In [46]:
Aadhaar_df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity,month
0,2025-03-01,andaman and nicobar islands,Andamans,744101,0,0,0,0,0,16,193,209,March
1,2025-03-01,andaman and nicobar islands,Nicobar,744301,0,0,0,32,360,101,48,541,March
2,2025-03-01,andaman and nicobar islands,Nicobar,744302,0,0,0,0,0,15,12,27,March
3,2025-03-01,andaman and nicobar islands,Nicobar,744303,0,0,0,0,0,46,27,73,March
4,2025-03-01,andaman and nicobar islands,Nicobar,744304,0,0,0,0,0,16,14,30,March
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2327255,2025-12-31,west bengal,West Midnapore,721426,0,1,0,0,0,0,0,1,December
2327256,2025-12-31,west bengal,West Midnapore,721504,1,0,0,0,0,0,0,1,December
2327257,2025-12-31,west bengal,West Midnapore,721506,1,1,0,0,0,0,0,2,December
2327258,2025-12-31,west bengal,West Midnapore,721507,1,0,0,0,0,0,0,1,December
2327259,2025-12-31,west bengal,West Midnapore,721517,2,1,0,0,0,0,0,3,December

In [47]:
Aadhaar_df['state'] = Aadhaar_df['state'].str.lower().str.strip()
Aadhaar_df['district'] = Aadhaar_df['district'].str.title().str.strip()
Aadhaar_df['month'] = Aadhaar_df['month'].str.title().str.strip()

keeping state,district and month column into lower and no space

In [48]:
Aadhaar_df.isna().sum()

date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
demo_age_5_17     0
demo_age_17_      0
bio_age_5_17      0
bio_age_17_       0
total_activity    0
month             0
dtype: int64

there is no null values

In [52]:
Aadhaar_df.duplicated(
    subset=['date','state','district','pincode']
).sum()

np.int64(943)

there are some duplicated in the data because of merging the 3 data sets we need to remove it 
before we cleaned individual duplicated now we are cleaning combined dataset duplicates

In [53]:
duplicate_rows = Aadhaar_df[
    Aadhaar_df.duplicated(
        subset=['date', 'state', 'district', 'pincode'],
        keep=False
    )
]

duplicate_rows.head(10)

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity,month
110515,2025-09-01,andaman and nicobar islands,South Andaman,744103,1,0,0,0,4,0,1,6,September
110516,2025-09-01,andaman and nicobar islands,South Andaman,744105,1,0,0,0,1,0,0,2,September
110517,2025-09-01,andaman and nicobar islands,South Andaman,744107,0,0,0,0,1,0,0,1,September
110518,2025-09-01,andaman and nicobar islands,South Andaman,744206,0,0,0,0,1,0,0,1,September
110519,2025-09-01,andaman and nicobar islands,South Andaman,744207,1,0,0,0,0,0,0,1,September
110533,2025-09-01,andaman and nicobar islands,South Andaman,744103,1,0,0,0,2,29,1,33,September
110534,2025-09-01,andaman and nicobar islands,South Andaman,744105,2,0,0,0,6,10,3,21,September
110536,2025-09-01,andaman and nicobar islands,South Andaman,744107,1,0,0,0,1,2,0,4,September
110538,2025-09-01,andaman and nicobar islands,South Andaman,744206,0,0,0,0,4,9,4,17,September
110539,2025-09-01,andaman and nicobar islands,South Andaman,744207,1,0,0,0,4,11,3,19,September

In [54]:
activity_cols = [
    'age_0_5','age_5_17','age_18_greater',
    'demo_age_5_17','demo_age_17_',
    'bio_age_5_17','bio_age_17_',
    'total_activity'
]

In [55]:
Aadhaar_df = Aadhaar_df.groupby(
    ['date', 'state', 'district', 'pincode', 'month'],
    as_index=False
)[activity_cols].sum()

In [56]:
Aadhaar_df.duplicated(
    subset=['date', 'state', 'district', 'pincode']
).sum()

np.int64(0)

there is no duplicates

In [57]:
Aadhaar_df

,date,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity
0,2025-03-01,andaman and nicobar islands,Andamans,744101,March,0,0,0,0,0,16,193,209
1,2025-03-01,andaman and nicobar islands,Nicobar,744301,March,0,0,0,32,360,101,48,541
2,2025-03-01,andaman and nicobar islands,Nicobar,744302,March,0,0,0,0,0,15,12,27
3,2025-03-01,andaman and nicobar islands,Nicobar,744303,March,0,0,0,0,0,46,27,73
4,2025-03-01,andaman and nicobar islands,Nicobar,744304,March,0,0,0,0,0,16,14,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2302102,2025-12-31,west bengal,West Midnapore,721426,December,0,1,0,0,0,0,0,1
2302103,2025-12-31,west bengal,West Midnapore,721504,December,1,0,0,0,0,0,0,1
2302104,2025-12-31,west bengal,West Midnapore,721506,December,1,1,0,0,0,0,0,2
2302105,2025-12-31,west bengal,West Midnapore,721507,December,1,0,0,0,0,0,0,1
2302106,2025-12-31,west bengal,West Midnapore,721517,December,2,1,0,0,0,0,0,3

In [58]:
Aadhaar_df = Aadhaar_df.groupby(
    ['date','state','district','pincode','month'],
    as_index=False
)[activity_cols + ['total_activity']].sum()

This code combines all Aadhaar records for the same date and location into a single row by adding up their activity numbers.
It gives one clear daily total for each pincode instead of many small records.

In [59]:
Aadhaar_df.shape

(2302107, 14)

In [60]:
Aadhaar_df.isna().sum()

date              0
state             0
district          0
pincode           0
month             0
age_0_5           0
age_5_17          0
age_18_greater    0
demo_age_5_17     0
demo_age_17_      0
bio_age_5_17      0
bio_age_17_       0
total_activity    0
total_activity    0
dtype: int64

In [61]:
Aadhaar_df.describe()

,date,pincode,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity,total_activity
count,2302107,2.302107e+06,2.302107e+06,2.302107e+06,2.302107e+06,2.302107e+06,2.302107e+06,2.302107e+06,2.302107e+06,2.302107e+06,2.302107e+06
mean,2025-10-25 20:06:59.088078336,5.232671e+05,1.538090e+00,7.469105e-01,7.302224e-02,2.110824e+00,1.928270e+01,1.485301e+01,1.539606e+01,5.400061e+01,5.400061e+01
min,2025-03-01 00:00:00,1.100010e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
25%,2025-09-20 00:00:00,3.930250e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,4.000000e+00
50%,2025-11-04 00:00:00,5.231690e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,2.000000e+00,2.000000e+00,1.200000e+01,1.200000e+01
75%,2025-12-05 00:00:00,6.885820e+05,1.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,1.200000e+01,8.000000e+00,8.000000e+00,3.600000e+01,3.600000e+01
max,2025-12-31 00:00:00,8.554560e+05,2.688000e+03,1.812000e+03,8.550000e+02,5.380000e+03,3.233200e+04,8.002000e+03,7.625000e+03,4.586100e+04,4.586100e+04
std,NaN,1.973599e+05,1.175132e+01,9.547031e+00,2.130413e+00,1.827644e+01,1.529500e+02,7.576201e+01,7.963820e+01,2.809834e+02,2.809834e+02

In [62]:
Aadhaar_df

,date,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity,total_activity
0,2025-03-01,andaman and nicobar islands,Andamans,744101,March,0,0,0,0,0,16,193,209,209
1,2025-03-01,andaman and nicobar islands,Nicobar,744301,March,0,0,0,32,360,101,48,541,541
2,2025-03-01,andaman and nicobar islands,Nicobar,744302,March,0,0,0,0,0,15,12,27,27
3,2025-03-01,andaman and nicobar islands,Nicobar,744303,March,0,0,0,0,0,46,27,73,73
4,2025-03-01,andaman and nicobar islands,Nicobar,744304,March,0,0,0,0,0,16,14,30,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2302102,2025-12-31,west bengal,West Midnapore,721426,December,0,1,0,0,0,0,0,1,1
2302103,2025-12-31,west bengal,West Midnapore,721504,December,1,0,0,0,0,0,0,1,1
2302104,2025-12-31,west bengal,West Midnapore,721506,December,1,1,0,0,0,0,0,2,2
2302105,2025-12-31,west bengal,West Midnapore,721507,December,1,0,0,0,0,0,0,1,1
2302106,2025-12-31,west bengal,West Midnapore,721517,December,2,1,0,0,0,0,0,3,3

In [63]:
Aadhaar_df.to_csv("cleaned_aadhaar_data.csv", index=False)