In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
Aadhaar_df=pd.read_csv(r'C:\Users\Lenovo\Desktop\UIDAI_Data_Hackathon_2026\data\combined\cleaned_aadhaar_data.csv')

In [3]:
Aadhaar_df['date'] = pd.to_datetime(Aadhaar_df['date'])

Aadhaar_df['day'] = Aadhaar_df['date'].dt.day
Aadhaar_df['weekday'] = Aadhaar_df['date'].dt.weekday      
Aadhaar_df['weekday_name'] = Aadhaar_df['date'].dt.day_name()
Aadhaar_df['is_weekend'] = Aadhaar_df['weekday'].isin([5,6]).astype(int)

Aadhaar_df['month_num'] = Aadhaar_df['date'].dt.month
Aadhaar_df['quarter'] = Aadhaar_df['date'].dt.quarter

In [4]:
Aadhaar_df.head()

,date,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,total_activity,total_activity.1,day,weekday,weekday_name,is_weekend,month_num,quarter
0,2025-03-01,andaman and nicobar islands,Andamans,744101,March,0,0,0,0,0,16,193,209,209,1,5,Saturday,1,3,1
1,2025-03-01,andaman and nicobar islands,Nicobar,744301,March,0,0,0,32,360,101,48,541,541,1,5,Saturday,1,3,1
2,2025-03-01,andaman and nicobar islands,Nicobar,744302,March,0,0,0,0,0,15,12,27,27,1,5,Saturday,1,3,1
3,2025-03-01,andaman and nicobar islands,Nicobar,744303,March,0,0,0,0,0,46,27,73,73,1,5,Saturday,1,3,1
4,2025-03-01,andaman and nicobar islands,Nicobar,744304,March,0,0,0,0,0,16,14,30,30,1,5,Saturday,1,3,1

In [5]:
Aadhaar_df['enrollment_total'] = Aadhaar_df[
    ['age_0_5','age_5_17','age_18_greater']
].sum(axis=1)

Aadhaar_df['demographic_total'] = Aadhaar_df[
    ['demo_age_5_17','demo_age_17_']
].sum(axis=1)

Aadhaar_df['biometric_total'] = Aadhaar_df[
    ['bio_age_5_17','bio_age_17_']
].sum(axis=1)

combining all ages into one total

In [6]:
Aadhaar_df.head()

,date,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,...,total_activity.1,day,weekday,weekday_name,is_weekend,month_num,quarter,enrollment_total,demographic_total,biometric_total
0,2025-03-01,andaman and nicobar islands,Andamans,744101,March,0,0,0,0,0,...,209,1,5,Saturday,1,3,1,0,0,209
1,2025-03-01,andaman and nicobar islands,Nicobar,744301,March,0,0,0,32,360,...,541,1,5,Saturday,1,3,1,0,392,149
2,2025-03-01,andaman and nicobar islands,Nicobar,744302,March,0,0,0,0,0,...,27,1,5,Saturday,1,3,1,0,0,27
3,2025-03-01,andaman and nicobar islands,Nicobar,744303,March,0,0,0,0,0,...,73,1,5,Saturday,1,3,1,0,0,73
4,2025-03-01,andaman and nicobar islands,Nicobar,744304,March,0,0,0,0,0,...,30,1,5,Saturday,1,3,1,0,0,30

In [7]:
Aadhaar_df['bio_share'] = Aadhaar_df['biometric_total'] / Aadhaar_df['total_activity']
Aadhaar_df['demo_share'] = Aadhaar_df['demographic_total'] / Aadhaar_df['total_activity']
Aadhaar_df['enroll_share'] = Aadhaar_df['enrollment_total'] / Aadhaar_df['total_activity']

what ever the total are there we making some percentile of each group

In [8]:
Aadhaar_df.head()

,date,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,...,weekday_name,is_weekend,month_num,quarter,enrollment_total,demographic_total,biometric_total,bio_share,demo_share,enroll_share
0,2025-03-01,andaman and nicobar islands,Andamans,744101,March,0,0,0,0,0,...,Saturday,1,3,1,0,0,209,1.000000,0.000000,0.0
1,2025-03-01,andaman and nicobar islands,Nicobar,744301,March,0,0,0,32,360,...,Saturday,1,3,1,0,392,149,0.275416,0.724584,0.0
2,2025-03-01,andaman and nicobar islands,Nicobar,744302,March,0,0,0,0,0,...,Saturday,1,3,1,0,0,27,1.000000,0.000000,0.0
3,2025-03-01,andaman and nicobar islands,Nicobar,744303,March,0,0,0,0,0,...,Saturday,1,3,1,0,0,73,1.000000,0.000000,0.0
4,2025-03-01,andaman and nicobar islands,Nicobar,744304,March,0,0,0,0,0,...,Saturday,1,3,1,0,0,30,1.000000,0.000000,0.0

In [9]:
Aadhaar_df[['bio_share','demo_share','enroll_share']] = (
    Aadhaar_df[['bio_share','demo_share','enroll_share']].fillna(0)
)

if there is any any null value fill with 0

In [10]:
Aadhaar_df['child_activity'] = Aadhaar_df['age_0_5'] + Aadhaar_df['age_5_17']
Aadhaar_df['adult_activity'] = Aadhaar_df['age_18_greater']

considering 0 -17 as child activity and 17+ as adult

In [11]:
pincode_mean = Aadhaar_df.groupby('pincode')['total_activity'].mean()

Aadhaar_df['pincode_avg_activity'] = Aadhaar_df['pincode'].map(pincode_mean)

First, this code calculates the average Aadhaar activity for each pincode.
Then, it assigns that average value back to every record of the same pincode.
This helps compare today’s activity with what is normally expected for that area

In [12]:
Aadhaar_df.head()

,date,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,...,quarter,enrollment_total,demographic_total,biometric_total,bio_share,demo_share,enroll_share,child_activity,adult_activity,pincode_avg_activity
0,2025-03-01,andaman and nicobar islands,Andamans,744101,March,0,0,0,0,0,...,1,0,0,209,1.000000,0.000000,0.0,0,0,21.642857
1,2025-03-01,andaman and nicobar islands,Nicobar,744301,March,0,0,0,32,360,...,1,0,392,149,0.275416,0.724584,0.0,0,0,16.622222
2,2025-03-01,andaman and nicobar islands,Nicobar,744302,March,0,0,0,0,0,...,1,0,0,27,1.000000,0.000000,0.0,0,0,5.982143
3,2025-03-01,andaman and nicobar islands,Nicobar,744303,March,0,0,0,0,0,...,1,0,0,73,1.000000,0.000000,0.0,0,0,12.581818
4,2025-03-01,andaman and nicobar islands,Nicobar,744304,March,0,0,0,0,0,...,1,0,0,30,1.000000,0.000000,0.0,0,0,6.280000

In [13]:
Aadhaar_df = Aadhaar_df.sort_values(['state','district','pincode','date'])

Aadhaar_df['lag_1_day'] = Aadhaar_df.groupby(
    ['state','district','pincode']
)['total_activity'].shift(1)

Aadhaar_df['lag_7_day'] = Aadhaar_df.groupby(
    ['state','district','pincode']
)['total_activity'].shift(7)

First, the data is sorted by location and date so that records are in time order.
Then, for each pincode, the previous day’s activity and the activity from 7 days ago are added as new columns.
This helps compare today’s Aadhaar activity with recent past trends and detect changes or spikes.

In [14]:
Aadhaar_df['rolling_7_mean'] = Aadhaar_df.groupby(
    ['state','district','pincode']
)['total_activity'].transform(lambda x: x.rolling(7).mean())

This code calculates the average Aadhaar activity over the last 7 days for each pincode.
It smooths daily ups and downs and shows the normal weekly activity level for that location.

In [15]:
threshold = Aadhaar_df['total_activity'].quantile(0.99)

Aadhaar_df['high_activity_flag'] = (
    Aadhaar_df['total_activity'] > threshold
).astype(int)

It flags the top 1% highest activity days to detect abnormal spikes.


This code finds the activity level that only the top 1% of days exceed.
Any day with activity higher than this level is marked as a high-activity day.
It helps quickly identify unusual spikes or special event days.

In [16]:
Aadhaar_df['state_code'] = Aadhaar_df['state'].astype('category').cat.codes
Aadhaar_df['district_code'] = Aadhaar_df['district'].astype('category').cat.codes

In [17]:
Aadhaar_df

,date,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,...,enroll_share,child_activity,adult_activity,pincode_avg_activity,lag_1_day,lag_7_day,rolling_7_mean,high_activity_flag,state_code,district_code
0,2025-03-01,andaman and nicobar islands,Andamans,744101,March,0,0,0,0,0,...,0.0,0,0,21.642857,NaN,NaN,NaN,0,0,37
22312,2025-04-01,andaman and nicobar islands,Andamans,744101,April,0,0,0,0,0,...,0.0,0,0,21.642857,209.0,NaN,NaN,0,0,37
43803,2025-05-01,andaman and nicobar islands,Andamans,744101,May,0,0,0,0,0,...,0.0,0,0,21.642857,184.0,NaN,NaN,0,0,37
65686,2025-06-01,andaman and nicobar islands,Andamans,744101,June,0,0,0,0,0,...,0.0,0,0,21.642857,140.0,NaN,NaN,0,0,37
87724,2025-07-01,andaman and nicobar islands,Andamans,744101,July,0,0,0,0,0,...,0.0,0,0,21.642857,140.0,NaN,NaN,0,0,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471155,2025-11-17,west bengal,West Midnapore,721641,November,0,0,0,0,0,...,0.0,0,0,17.822642,1.0,NaN,1.000000,0,35,973
1521576,2025-11-19,west bengal,West Midnapore,721641,November,0,0,0,0,2,...,0.0,0,0,17.822642,1.0,1.0,1.142857,0,35,973
1865127,2025-12-10,west bengal,West Midnapore,721641,December,0,0,0,0,2,...,0.0,0,0,17.822642,2.0,1.0,1.285714,0,35,973
1985744,2025-12-15,west bengal,West Midnapore,721641,December,1,0,0,0,0,...,1.0,1,0,17.822642,2.0,1.0,1.285714,0,35,973
314998,2025-09-09,west bengal,West Midnapore,721663,September,0,0,0,0,0,...,0.0,0,0,2.596491,NaN,NaN,NaN,0,35,973

In [18]:
Aadhaar_df["high_activity_flag"].value_counts()

high_activity_flag
0    2279105
1      23002
Name: count, dtype: int64

#### Around 99% of the days have normal Aadhaar activity, while about 1% show unusually high spikes, likely due to special drives or events.

In [19]:
Aadhaar_df.to_csv("feature_engineered_aadhaar_data.csv", index=False)